Vagrant.configure('2') do |config|
  config.vm.box = 'debian/bookworm64'
  config.vm.hostname = 'debian-12.my-domain'
  
  config.vm.provider 'virtualbox' do |vb|
    vb.name = 'debian-12'
    vb.memory = '2048'
    vb.cpus = 2
    vb.customize ['modifyvm', :id, '--natdnshostresolver1', 'on']
    vb.customize ['modifyvm', :id, '--nic1', 'nat']
    vb.customize [
      'modifyvm', :id,
      '--nic2', 'hostonly',
      '--hostonlyadapter2', 'vboxnet0'
    ]
  end

  config.vm.network 'private_network', 
    ip: '192.168.56.70',
    virtualbox__intnet: 'vboxnet0'
end




